### PR TITLE
Minor: fixed ui

### PR DESCRIPTION
**Pull request by nermalcat69**
changes
- fixed navbar
- added svg logo
- fixed margins and paddings
- fixed font sizes
- fixed cards

### CODE REVIEW

**Comment by nermalcat69** [comment]
Uhhh conflicts

**Comment by nermalcat69** [comment]
also i plan on ditching bulma, i hope you guys dont mind it

**Comment by Bhupesh-V** [comment]
> also i plan on ditching bulma, i hope you guys dont mind it

Please open a separate issue before doing anything on this area, we need to understand why we need to remove bulma, what are the alternatives, how easy is to maintain code in alternatives.

PS: I see there are a lot of opinionated code lint changes like this, maybe undo them because I don't think anyone has their editor setup to do them

```
<link
      rel="canonical"
      href="{{ url_for(request.endpoint, _external=True) }}"
    />
```

**Comment by Bhupesh-V** [comment]
@nermalcat69 Please attach screenshots of changes made

**Comment by nermalcat69** [comment]
sureee i'll do that when i get time, thanks for replying

**Comment by nermalcat69** [comment]
> > also i plan on ditching bulma, i hope you guys dont mind it
> 
> Please open a separate issue before doing anything on this area, we need to understand why we need to remove bulma, what are the alternatives, how easy is to maintain code in alternatives.
> 
> PS: I see there are a lot of opinionated code lint changes like this, maybe undo them because I don't think anyone has their editor setup to do them
> 
> ```
> <link
>       rel="canonical"
>       href="{{ url_for(request.endpoint, _external=True) }}"
>     />
> ```

yeah sureee i'll do that abt how we should replace it with just plain css or just tailwind css

**Comment by nermalcat69** [comment]
Before: https://cdn.discordapp.com/attachments/1194312262102556782/1222332066235158539/image.png?ex=6615d472&is=66035f72&hm=9018f44758b3cd7263332e2b8a15fa519c4f552316db313c16d861983502a314&
After: https://cdn.discordapp.com/attachments/1194312262102556782/1222332005643976734/image.png?ex=6615d463&is=66035f63&hm=b0544e009846b8cd14f427fba19254ffb2d18a5315fef5d6826554639120ba7b&

**Comment by nermalcat69** [comment]
## Before
before

## After
after

**Comment by nermalcat69** [comment]
## Before




## After

**Comment by nermalcat69** [comment]
Review this pr, i'll open the issue for replacing bulma later :3

**Pull request closed without merging**
