### PR TITLE
Fixed Footer Styling to stick it to the bottom

### LINKED ISSUE #12: Footer not sticking to bottom
### What happened?

Footer in the site isn't fixed to the bottom

Screenshot_20230206_174944

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### PR DESCRIPTION
**Pull request by ansid0102**
## Description

Fixed Footer Styling to stick it to the bottom

Fixes #12 

## Changes Include

- [x] Bug fix 🐛 (non-breaking change which fixes an issue)
- [ ] New feature ✨ (non-breaking change which adds functionality)
- [ ] Breaking change 😢 (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor ⚒️ (code change that neither fixes a bug nor adds a feature)
- [ ] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)
- [ ] Performance ⚡ (code change that improves performance)
- [ ] This change requires a documentation update 📖

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Screenshots (if any)
image

(prefer animated gif)

### CODE REVIEW

**Review by Bhupesh-V — CHANGES_REQUESTED** [review]
Merging this will introduce a bug where the footer overrides some content on the page. Can you address this, maybe?

Screenshot 2023-02-06 at 7 58 36 PM


Screenshot 2023-02-06 at 7 58 36 PM

**Review by siduck — APPROVED** [review]

**Comment by ansid0102** [comment]
Yeah! I'll try to fix it

**Comment by ansid0102** [comment]
I think we can make the container class

**Comment by ansid0102** [comment]
I think now it is perfect and flawless I tried it with some static content. Now the stuff sticks to bottom without overlapping.

**Comment by Bhupesh-V** [comment]
> I think now it is perfect and flawless I tried it with some static content. Now the stuff sticks to bottom without overlapping.

It's still the same, did you try to run the app locally? Adding static content might not help test the fix. Please use github codespaces to run the project (follow installation instructions in readme)

Please provide screenshots if possible!

**Comment by ansid0102** [comment]
image

image

Tell me if this is good now. I think now it is perfect.

**Comment by ansid0102** [comment]
image

**Comment by siduck** [comment]
> image

I think it would look better if the footer had top mrgin

**Comment by ansid0102** [comment]
> 

Yes will add that.

**Comment by Bhupesh-V** [comment]
@ansid0102 Yes, it looks good now 👍🏽
Thanks for the feedback @siduck 

I think we are good to go 🚀

**Review by Bhupesh-V — APPROVED** [review]

**Comment by Bhupesh-V** [comment]
@all-contributors please add @ansid0102  for code

**Pull request merged**
